package com.study.store.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.study.store.dto.ItemDto;
import lombok.*;

import java.io.Serializable;
import java.util.List;

@Data
@Builder
@ToString
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "order")
public class Order implements Serializable {

    @DynamoDBHashKey(attributeName = "order_id")
    @DynamoDBAutoGeneratedKey
    private String orderId;

    @DynamoDBAttribute(attributeName = "customer_id")
    private String customerId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private List<Item> items;
}
